### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by anonymous789456** [keru6k/SodiumExecutor#1]
icant open the file what is the password

**Comment by keru6k** [comment]
you can remove the whole authentication thing by configuring Program.cs
However, if you don't want to do all of that, here's the key: SSE3Yk8ckFUuze67ErebLWSzvSHUApMXzEboBy8QG

        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Sodium()); # replace Sodium with ExecutorUI
        }
    }

**Comment by anonymous789456** [comment]
thanks bro
